import random

def greeting_gen():
  greetings = [
      "Hello. It’s a pleasure to meet you. How can I assist you today?",
      "Greetings. I trust you are doing well. How may I help you today?",
      "Salutations. I hope you are in good spirits. How can I be of service today?",
      "Welcome. It’s great to connect with you. How can I help you today?",
      "Hi there. I hope all is well with you. What can I assist you with today?",
      "Good to see you. I hope you’re having a wonderful day. How may I support you today?",
      "Hello there. I hope this message finds you well. How can I help you today?",
      "Hi. I’m glad to connect with you. How may I assist you today?",
      "Hello. I appreciate the opportunity to connect. How can I assist you today?",
      "Greetings. It’s a pleasure to be in touch. How may I help you today?",
      "Salutations. I’m here to help. How can I be of service today?",
      "Welcome. Thank you for reaching out. How can I assist you today?",
      "Hi. It’s wonderful to speak with you. How may I support you today?",
      "Hello. I hope this finds you well. How can I help you today?",
      "Greetings. I look forward to assisting you. How may I help you today?",
      "Salutations. Thank you for your time. How can I be of service today?",
      "Welcome. I’m here to assist you. How can I help you today?",
      "Hi there. It’s nice to connect. What can I assist you with today?",
      "Good to see you. I’m eager to help. How may I support you today?",
      "Hello there. I’m here for you. How can I help you today?",
      "Hi. Thank you for reaching out. How may I assist you today?",
      "Hello. It’s a pleasure to connect with you. How can I be of service today?",
      "Greetings. I’m glad to assist you. How can I help you today?",
      "Salutations. Thank you for this opportunity. How may I help you today?",
      "Welcome. I appreciate your inquiry. How can I assist you today?",
      "Hi. It’s great to be in touch. What can I help you with today?",
      "Hello. I hope you’re doing well. How can I support you today?",
      "Greetings. I’m pleased to be here. How may I help you today?",
      "Salutations. I’m at your service. How can I assist you today?",
      "Welcome. I’m here to help. How can I support you today?",
      "Hi there. It’s wonderful to connect. How may I assist you today?",
      "Good to see you. I’m ready to help. What can I assist you with today?",
      "Hello there. I’m pleased to assist you. How can I help you today?",
      "Hi. Thank you for this opportunity. How may I support you today?",
      "Hello. I’m here to assist. How can I be of service today?",
      "Greetings. It’s an honor to connect. How can I help you today?",
      "Salutations. I’m eager to assist you. How may I help you today?",
      "Welcome. I appreciate your reaching out. How can I assist you today?",
      "Hi there. I’m glad to connect. What can I help you with today?",
      "Good to see you. I’m here to support you. How may I assist you today?",
      "Hello there. I hope all is well. How can I help you today?",
      "Hi. Thank you for your time. How may I assist you today?",
      "Hello. I’m delighted to connect. How can I be of service today?",
      "Greetings. I’m here to help. How can I assist you today?",
      "Salutations. I look forward to assisting you. How may I help you today?",
      "Welcome. It’s a pleasure to meet you. How can I support you today?",
      "Hi there. I appreciate this opportunity. What can I assist you with today?",
      "Good to see you. I’m here for you. How can I help you today?",
      "Hello there. Thank you for connecting. How may I assist you today?",
      "Hi. It’s a pleasure to speak with you. How can I support you today?"
  ]

  greeting = random.choice(greetings)

  return greeting